name: houston_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  serverpod_client: 2.8.0
  serverpod_auth_client: 2.8.0
  serverpod_auth_shared_flutter: 2.8.0
  serverpod_auth_email_flutter: 2.8.0
