name: houston_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod_client: 1.2.6
  serverpod_auth_client: 1.2.6
  serverpod_auth_shared_flutter: 1.2.6
  serverpod_auth_email_flutter: 1.2.6

