# Generated by Django 5.0.6 on 2024-05-20 02:39

import project.utils.uuid
import project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=project.utils.uuid.get_uuid, editable=False, unique=True, verbose_name='UUID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, validators=[project.validators.TypeValidator(dict)], verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('image_url', models.URLField(verbose_name='Image Url')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
