CREATE TABLE IF NOT EXISTS "public"."game_system" (
"id" bigint NOT NULL,
"uid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
"name" character varying NOT NULL,
"price" numeric NOT NULL,
"description" "text" NOT NULL,
"image_url" "text" NOT NULL,
"created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."game_system" OWNER TO "postgres";
ALTER TABLE "public"."game_system" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
SEQUENCE NAME "public"."game_system_id_seq"
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1
);
ALTER TABLE ONLY "public"."game_system" ADD CONSTRAINT "game_system_pkey" PRIMARY KEY ("id");