CREATE TABLE IF NOT EXISTS "public"."game" (
"id" bigint NOT NULL,
"uid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
"game_system" bigint NOT NULL,
"name" character varying NOT NULL,
"price" numeric NOT NULL,
"description" "text" NOT NULL,
"players" numeric NOT NULL,
"image_url" "text" NOT NULL,
"created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."game" OWNER TO "postgres";
ALTER TABLE "public"."game" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
SEQUENCE NAME "public"."game_id_seq"
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1
);
ALTER TABLE ONLY "public"."game" ADD CONSTRAINT "game_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."game" ADD CONSTRAINT "game_game_system_fkey" FOREIGN KEY ("game_system") REFERENCES "public"."game_system"("id") ON DELETE CASCADE;