CREATE TABLE IF NOT EXISTS "public"."profile" (
"id" bigint NOT NULL,
"uid" "uuid" NOT NULL references auth.users ON DELETE CASCADE,
"username" character varying NOT NULL,
"first_name" character varying NOT NULL DEFAULT '',
"last_name" character varying NOT NULL DEFAULT '',
"avatar" character varying NOT NULL DEFAULT '',
"bio" "text",
"created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."profile" OWNER TO "postgres";
ALTER TABLE "public"."profile" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
SEQUENCE NAME "public"."profile_id_seq"
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1
);
ALTER TABLE ONLY "public"."profile" ADD CONSTRAINT "profile_pkey" PRIMARY KEY ("id");