# Generated by Django 5.0.6 on 2024-05-19 02:05

import phonenumber_field.modelfields
import project.fields
import project.utils.uuid
import project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=project.utils.uuid.get_uuid, editable=False, unique=True, verbose_name='UUID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, validators=[project.validators.TypeValidator(dict)], verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('email', project.fields.CIEmailField(blank=True, db_index=True, max_length=128, null=True, unique=True, verbose_name='Email')),
                ('username', models.CharField(db_index=True, max_length=128, verbose_name='Username')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, null=True, region=None, unique=True, verbose_name='Number')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='Name')),
                ('image', models.URLField(blank=True, max_length=256, verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user can access their account.', verbose_name='Active')),
                ('is_setup', models.BooleanField(default=False, help_text='Designates whether the user requires onboarding.', verbose_name='Setup')),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
