# Generated by Django 5.0.6 on 2024-05-21 20:07

import phonenumber_field.modelfields
import project.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=project.fields.CIEmailField(db_index=True, default='tyler@tylersavery.com', max_length=128, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, unique=True, verbose_name='Number'),
        ),
    ]
