# Generated by Django 5.0.6 on 2025-06-23 19:43

import project.utils.string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_user_email_alter_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_code',
            field=models.CharField(default=project.utils.string.generate_random_digits),
        ),
    ]
