# Generated by Django 5.0.6 on 2025-06-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_user_email_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
